Bump to 0.4, add cluster-setup with CentOS 7 support
git-svn-id: file:///home/bacon/SVN/spcm/cluster-admin-0.4@499 fc83dafb-f549-e211-8a70-0017315c2eee

diff --git a/CentOS/Sys-scripts/cluster-setup b/CentOS/Sys-scripts/cluster-setup
--- a/CentOS/Sys-scripts/cluster-setup
+++ b/CentOS/Sys-scripts/cluster-setup
@@ -93,58 +93,6 @@ line()
 
 ##########################################################################
 #   Function description:
-#       Convenience pkgsrc installer
-#
-#   Arguments:
-#       1)  category
-#       2)  package
-#
-#   Returns:
-#       NA: Whole script terminates on first failed command
-#
-#   History:
-#   Date        Name        Modification
-#   2013-02-15  Jason Bacon Begin
-##########################################################################
-
-pkgsrc_install_packages()
-{
-    if [ $# -lt 3 ]; then
-	printf "Usage: pkgsrc_install_packages pkgsrc-prefix pkgsrc-suffix category/package [category/package ...]\n"
-	exit 1
-    fi
-
-    local pkgsrc_prefix=$1
-    local pkgsrc_suffix=$2
-
-    shift
-    for pkg in $@; do
-	line
-	if pkg_info `basename $pkg`; then
-	    printf "$pkg is already installed.\n"
-	else
-	    printf "Installing $pkg...\n"
-	    pkg_name=`echo $pkg | cut -d '/' -f 2`
-	    pkg_path=$pkgsrc_prefix/pkgsrc${pkgsrc_suffix}/packages/All/$pkg_name*.tgz
-	    save_cwd=`pwd`
-	    cd $pkgsrc_prefix/pkgsrc${pkgsrc_suffix}/$pkg
-	    if [ -e "$pkg_path" ]; then
-		printf "Using binary package $pkg_path...\n"
-		bmake bin-install
-	    else
-		printf "Building $pkg from source...\n"
-		env ALLOW_VULNERABLE_PACKAGES=yes bmake install
-	    fi
-	    #bmake clean
-	    #bmake clean-depends
-	    cd $save_cwd
-	fi
-    done
-}
-
-
-##########################################################################
-#   Function description:
 #       
 #   Arguments:
 #       
@@ -154,60 +102,20 @@ pkgsrc_install_packages()
 #   Date        Name        Modification
 #   2013-12-10  bacon        Begin
 ##########################################################################
+
 
 pkgsrc_setup()
 {
-    if [ $# != 2 ]; then
-	printf "Usage: pkgsrc_setup prefix suffix\n"
-	exit 1
-    fi
-    
     line
-    local pkgsrc_prefix=$1
-    local pkgsrc_prefix=$2
+    auto-binary-pkgsrc-setup /usr/pkg gcc-5.0
 
-    if [ ! -e $pkgsrc_prefix/pkg ]; then
-	printf "Installing pkgsrc in $pkgsrc_prefix...\n"
-	auto-pkgsrc-setup $pkgsrc_prefix
+    # Add pkgsrc to default path, non-exclusive
+    if [ -e /etc/profile.d ]; then
+	ln -sf /usr/pkg/etc/pkgsrc-non-exclusive.* /etc/profile.d
     fi
     
-    # FIXME: restore PATH after install in case this function is
-    # executed more than once.
-    # old_path=$PATH
-    export PATH=${PATH}:$pkgsrc_prefix/pkg${pkgsrc_suffix}/bin:$pkgsrc_prefix/pkg${pkgsrc_suffix}/sbin
-    # export PATH=$old_path
-}
-
-
-##########################################################################
-#   Function description:
-#       Source new env script to add pkgsrc bins to PATH, etc.
-#       
-#   History:
-#   Date        Name        Modification
-#   2013-12-10  bacon        Begin
-##########################################################################
-
-pkgsrc_append_default_path()
-{
-    if [ $# != 2 ]; then
-	printf "Usage: pkgsrc_append_default_path prefix suffix\n"
-	exit 1
-    fi
-    
-    # Add Pkgsrc binaries to path
-    line
-    local pkgsrc_prefix=$1
-    local pkgsrc_suffix=$2
-    
-    # Done by auto-pkgsrc-setup
-    # printf "Installing startup scripts...\n"
-    # cp $pkgsrc_prefix/pkg${pkgsrc_suffix}/etc/pkgsrc.*sh /etc/profile.d
-    # chmod +x /etc/profile.d/pkgsrc.*sh
-    # . /etc/profile
-    
-    . $pkgsrc_prefix/pkg${pkgsrc_suffix}/etc/pkgsrc.sh
-    return 0
+    # Add pkgsrc to current path, exclusive
+    . /usr/pkg/etc/pkgsrc.sh
 }
 
 
@@ -224,11 +132,12 @@ ib_config()
 {
     # Can we avoid using a groupinstall and just install the essential packages?
     # Are these necessary, or do we just need to enable rdma?
+    # Obsolete: libibmad-devel
     yum groupinstall -y "Infiniband Support"
     yum install -y \
 	libibverbs-devel \
 	libibcommon-devel \
-	libibmad-devel \
+	infiniband-diags-devel \
 	libibcm-devel \
 	librdmacm-devel \
 	infiniband-diags \
@@ -238,11 +147,28 @@ ib_config()
     # yum install -y srptools rdma
     
     # Required for ib
-    chkconfig ibacm on
-    chkconfig rdma on
-    service ibacm stop
-    service rdma restart
-    service ibacm start
+    case $OS_RELEASE in
+    RHEL6)
+	chkconfig ibacm on
+	chkconfig rdma on
+	service ibacm stop
+	service rdma restart
+	service ibacm start
+	;;
+    RHEL7)
+	systemctl enable ibacm.service
+	systemctl enable rdma.service
+	systemctl stop ibacm.service
+	# Failed to restart rdma.service: Operation refused, unit rdma.service
+	# may be requested by dependency only (it is configured to refuse
+	# manual start/stop).
+	# systemctl restart rdma.service
+	systemctl start ibacm.service
+	;;
+    *)
+	printf "Unsupported RHEL version: $OS_RELEASE\n"
+	exit 1
+    esac
     
     # SCSI RDMA protocol
     # Set SRP_LOAD=yes in /etc/rdma/rdma.conf
@@ -261,7 +187,7 @@ ib_config()
     interface=`auto-ask eth-int 'Local Ethernet interface?' $default_if`
     current_ip=`ip addr show $interface | awk '$1 == "inet" { print $2 }' | awk -F / ' { print $1 }'`
     # FIXME: Specific to x.y.1.z networks
-    ib_ip=`printf "$current_ip" | awk -F '.' ' { printf("%d.2.%d.%d",$1,$3,$4); }'`
+    ib_ip=`printf "$current_ip" | awk -F '.' ' { printf("%d.%d.%d.%d",$1,$2,$3+128,$4); }'`
     ib_ip=`auto-ask ib-ip 'ib0 IP address?' $ib_ip`
     
     # FIXME: Unmount NFS shares on ib0 first
@@ -277,11 +203,8 @@ ib_config()
     #if egrep 'DEVICE|HWADDR|TYPE|UUID' $file-ib0 > temp-ib0; then
     #    printf "Preserving existing ib0 settings.\n"
     #fi
-    #mv temp-ib0 $file-ib0
-    # FIXME
     hwaddr=`ip addr show ib0 | awk '$1 == "link/infiniband" { print $2 }'`
-    # FIXME: Make this user input
-    netmask='255.255.252.0'
+    netmask='255.255.192.0'
     netmask=`auto-ask ib-netmask 'ib0 netmask?' $netmask`
     cat << EOM > $file-ib0
 DEVICE=ib0
@@ -295,9 +218,20 @@ CONNECTED_MODE=yes
 EOM
     # Causes network to hang if done remotely
     # Start ib0 by other means
-    # service network restart
     ip link set ib0 up
-    service network restart
+    
+    case $OS_RELEASE in
+    RHEL6)
+	service network restart
+	;;
+    RHEL7)
+	systemctl restart network.service
+	;;
+    *)
+	printf "Unsupported RHEL version: $OS_RELEASE\n"
+	exit 1
+    esac
+    
     ip addr show ib0
     
     # Add ib interface to /etc/hosts
@@ -327,9 +261,21 @@ ntp_config()
     # Start with correct date
     yum install -y ntp ntpdate
     ntpdate -u pool.ntp.org
-    chkconfig ntpd on
-    service ntpd stop
-    service ntpd start
+    case $OS_RELEASE in
+    RHEL6)
+	chkconfig ntpd on
+	# FIXME: Why not restart?
+	service ntpd stop
+	service ntpd start
+	;;
+    RHEL7)
+	systemctl enable ntpd
+	systemctl restart ntpd.service
+	;;
+    *)
+	printf "Unsupported RHEL version: $OS_RELEASE\n"
+	exit 1
+    esac
 }
 
 
@@ -383,17 +329,43 @@ nfs_config()
     
     idmapd_domain=`auto-ask idmapd-domain 'IDMAPD domain for NFS4?' cluster`
     sed -i "s|.*Domain = .*|Domain = $idmapd_domain|" /etc/idmapd.conf
-    service rpcidmapd restart
+    
+    case $OS_RELEASE in
+    RHEL6)
+	service rpcidmapd restart
+	;;
+    RHEL7)
+	systemctl restart rpcidmapd.service
+	;;
+    *)
+	printf "Unsupported RHEL version: $OS_RELEASE\n"
+	exit 1
+    esac
 
-    chkconfig rpcbind on
-    chkconfig nfslock on
-    chkconfig nfs on
+    case $OS_RELEASE in
+    RHEL6)
+	chkconfig rpcbind on
+	chkconfig nfslock on
+	chkconfig nfs on
+	;;
+    RHEL7)
+	systemctl enable rpcbind
+	systemctl enable nfslock
+	systemctl enable nfs
+	;;
+    *)
+	printf "Unsupported RHEL version: $OS_RELEASE\n"
+	exit 1
+    esac
 
     # Configure shared directories
     case $NODE_TYPE in
     'head'|'io')
-	default_range='192.168.0.0/22'
+	default_range='192.168.0.0/16'
 	range=`auto-ask nfs-range 'NFS export range?' $default_range`
+	
+	printf '\nCurrent local mounts:\n\n'
+	df -l
 	
 	printf '\nCurrent exports:\n\n'
 	cat /etc/exports
@@ -410,9 +382,21 @@ nfs_config()
 		/etc/exports $0
 	done
 	    
-	service rpcbind restart
-	service nfslock restart
-	service nfs restart
+	case $OS_RELEASE in
+	RHEL6)
+	    service rpcbind restart
+	    service nfslock restart
+	    service nfs restart
+	    ;;
+	RHEL7)
+	    systemctl restart rpcbind.service
+	    systemctl restart nfslock.service
+	    systemctl restart nfs
+	    ;;
+	*)
+	    printf "Unsupported RHEL version: $OS_RELEASE\n"
+	    exit 1
+	esac
     
 	# Signal NFS daemon to update exports
 	# Unnecessary after restarting daemons?
@@ -448,10 +432,22 @@ nfs_config()
 	    done
 	fi
 	
-	service rpcbind restart
-	service nfslock restart
-	service nfs restart
-    
+	case $OS_RELEASE in
+	RHEL6)
+	    service rpcbind restart
+	    service nfslock restart
+	    service nfs restart
+	    ;;
+	RHEL7)
+	    systemctl restart rpcbind.service
+	    systemctl restart nfslock.service
+	    systemctl restart nfs
+	    ;;
+	*)
+	    printf "Unsupported RHEL version: $OS_RELEASE\n"
+	    exit 1
+	esac
+
 	# mount and test
 	mount -a
 	df
@@ -484,7 +480,7 @@ install_core_rpms()
 	nano \
 	sysstat \
 	bind-utils \
-	dash ksh tcsh zsh \
+	ksh tcsh zsh \
 	finger \
 	bc \
 	mailx \
@@ -505,7 +501,7 @@ install_core_rpms()
     line
     printf "Installing base development tools...\n"
     # gcc-* and cvs required for pkgsrc
-    yum install -y gcc gcc-c++ gcc-gfortran cvs subversion
+    yum install -y gcc gcc-c++ gcc-gfortran cvs gdb
 
     # Enable X11 apps without installing a desktop system like KDE
     line
@@ -531,9 +527,21 @@ ssh_config()
     # Enable incoming ssh
     line
     printf 'Configuring sshd...\n'
-    chkconfig sshd on
-    service sshd restart
     
+    case $OS_RELEASE in
+    RHEL6)
+	chkconfig sshd on
+	service sshd restart
+	;;
+    RHEL7)
+	systemctl enable sshd.service
+	systemctl restart sshd.service
+	;;
+    *)
+	printf "Unsupported RHEL version: $OS_RELEASE\n"
+	exit 1
+    esac
+
     # Enable passwordless ssh so we can distribute hosts entries below
     if [ ! -e /root/.ssh/id_rsa ]; then
 	printf "Setting up public key...\n"
@@ -577,72 +585,12 @@ EOM
 #       
 #   History:
 #   Date        Name        Modification
-#   2013-12-11  bacon        Begin
-##########################################################################
-
-ldap_config()
-{
-    # Enable ldap authentication for ssh.  OS and dist dependent!
-    # Add to auto-admin Linux tools
-    # http://www.centos.org/docs/5/html/Deployment_Guide-en-US/s1-ldap-pam.html
-
-    # Redhat/CentOS
-    yum install -y openldap-clients.x86_64
-
-    # Edit /etc/ldap.conf, /etc/openldap/ldap.conf, etc.
-    ldap=`auto-ask ldap 'Enable LDAP authentication?' y`
-    if [ $ldap = 'y' ]; then
-	server=`auto-ask ldap-server 'LDAP server?' ldap://ldap.my.domain`
-	ou=`auto-ask ldap-ou 'Organization info?' ou=people,o=my.domain`
-	cert_file=`auto-ask cert 'Name of CERT file?' ./cacert.crt`
-	auto-ldap-client-setup $server $ou $cert_file
-    fi
-}
-
-
-##########################################################################
-#   Function description:
-#       
-#   Arguments:
-#       
-#   Returns:
-#       
-#   History:
-#   Date        Name        Modification
 #   2014-05-02  bacon        Begin
 ##########################################################################
 
 cluster_startup_scripts()
 {
-    ln -sf $pkgsrc_prefix/pkg${pkgsrc_suffix}/etc/profile.d/* /etc/profile.d
-}
-
-
-##########################################################################
-#   Function description:
-#       
-#   Arguments:
-#       
-#   Returns:
-#       
-#   History:
-#   Date        Name        Modification
-#   2014-05-02  bacon        Begin
-##########################################################################
-
-apache_install()
-{
-    if [ $# != 2 ]; then
-	printf "Usage: apache_install pkgsrc-prefix\n"
-	exit 1
-    fi
-    
-    local pkgsrc_prefix=$1
-    local pkgsrc_suffix=$2
-
-    pkgsrc_install_packages $pkgsrc_prefix "$pkgsrc_suffix" www/apache24
-    
-    # FIXME: Install proper init script
+    ln -sf /usr/pkg/etc/profile.d/* /etc/profile.d
 }
 
 
@@ -660,18 +608,10 @@ apache_install()
 
 slurm_install()
 {
-    if [ $# != 2 ]; then
-	printf "Usage: slurm_install pkgsrc-prefix pkgsrc-suffix\n"
-	exit 1
-    fi
-    
-    local pkgsrc_prefix=$1
-    local pkgsrc_suffix=$2
-    
     case $NODE_TYPE in
     'head'|'compute')
 	if ! pkg_info -e slurm; then
-	    pkgsrc_install_packages $pkgsrc_prefix "$pkgsrc_suffix" wip/slurm
+	    pkgin install -y slurm-wlm
 	else
 	    if ! fgrep slurm /etc/passwd; then
 		printf "Run node-sync-user `hostname` slurm from the head node\n"
@@ -679,7 +619,7 @@ slurm_install()
 	    fi
 	fi
 	cluster-munge-enable $NODE_TYPE
-	cluster-slurm-enable
+	cluster-slurm-enable $NODE_TYPE
 	;;
     'io')
 	;;
@@ -701,28 +641,42 @@ slurm_install()
 
 ganglia_install()
 {
-    if [ $# != 2 ]; then
-	printf "Usage: ganglia_install pkgsrc-prefix pkgsrc-suffix\n"
+    if [ $# != 0 ]; then
+	printf "Usage: ganglia_install\n"
 	exit 1
     fi
-    local pkgsrc_prefix=$1
-    local pkgsrc_suffix=$2
     
     # Redundant check due to name diff between pkg and port
     if ! pkg_info ganglia-monitor-core > /dev/null; then
-	pkgsrc_install_packages $pkgsrc_prefix "$pkgsrc_suffix" \
-	    wip/ganglia-monitor-core
+	pkgin install -y ganglia-monitor-core
     fi
 
-    # Required for "service gmond"
-    ln -sf $pkgsrc_prefix/pkg${pkgsrc_suffix}/share/examples/ganglia-monitor-core/gmond.init.linux \
-	/etc/init.d/gmond
-    chkconfig --add gmond
-    chkconfig gmond on
-    service gmond restart
-    
+    case $OS_RELEASE in
+    RHEL6)
+	ln -sf /usr/pkg/share/examples/ganglia/gmond.init.linux \
+	    /etc/init.d/gmond
+	chkconfig --add gmond
+	chkconfig gmond on
+	service gmond restart
+	;;
+    RHEL7)
+	# FIXME: Is there a systemctl service script?
+	# FIXME: ganglia pkg should create this
+	mkdir -p /usr/pkg/var/run/
+	systemctl disable gmond.service || true
+	systemctl enable /usr/pkg/share/examples/ganglia/gmond.service
+	systemctl daemon-reload
+	systemctl restart gmond.service
+	;;
+    *)
+	printf "Unsupported RHEL version: $OS_RELEASE\n"
+	exit 1
+    esac
+
     if [ $NODE_TYPE = head ]; then
-	pkgsrc_install_packages $pkgsrc_prefix "$pkgsrc_suffix" wip/ganglia-web
+	# FIXME: Commit ganglia and just install that
+    
+	pkgin install -y ganglia-webfrontend
 	ganglia-web-setup
     fi
 }
@@ -795,30 +749,6 @@ EOM
 
 
 ##########################################################################
-#   Function description:
-#       
-#   Arguments:
-#       
-#   Returns:
-#       
-#   History:
-#   Date        Name        Modification
-#   2016-08-15  root        Begin
-##########################################################################
-
-iptables_config()
-{
-    if ! iptables-save | grep -- "-j CLUSTER"; then
-	iptables -N CLUSTER
-	iptables -I INPUT $INSERTLN -j CLUSTER
-	iptables -I CLUSTER -p udp -s 192.168.0.0/22 -j ACCEPT
-	iptables -I CLUSTER -p tcp -s 192.168.0.0/22 -j ACCEPT
-	/etc/init.d/iptables save
-    fi
-}
-
-
-##########################################################################
 #   Main
 ##########################################################################
 
@@ -834,12 +764,25 @@ if [ $# != 1 ]; then
     usage $0
 fi
 
+cat << EOM
+
+This is a new cluster-setup script, heavily modified from the original.
+It has not been tested on CentOS 6.  Use cluster-setup.old to ensure
+compatibiliity.
+
+Proceed with caution and watch for issues!
+
+EOM
+pause
+
 # Caution: 
 # The line below is modified by install.sh. Be careful not to replace
 # %%PREFIX%% with a hard-coded prefix from an installed script.
-prefix=/usr/pkg-1
+prefix=/usr/pkg
 
 NODE_TYPE=$1
+OS_RELEASE=`auto-os-release`
+
 case $NODE_TYPE in
 'head'|'compute'|'io')
     ;;
@@ -848,7 +791,7 @@ case $NODE_TYPE in
     ;;
 esac
 
-if [ -e /root/Save/anaconda-ks.cfg ]; then
+if [ -e /root/Save/node-configured ]; then
     printf "Node already configured.  Reconfigure? [n] "
     read reconfig
     if [ 0$reconfig != 0y ]; then
@@ -886,10 +829,25 @@ export PATH=${PATH}:$START_DIR
 boot_block_backup
 ntp_config
 install_core_rpms
-auto-enable-passwdqc
+pkgsrc_setup
+
+# Install cluster-admin and other wip packages
+pkgin install -y subversion
+cd /usr/pkgsrc
+svn co https://outpaddling@github.com/outpaddling/uwm-pkgsrc-wip/trunk \
+	uwm-pkgsrc-wip
+for pkg in cluster-admin ape; do
+    cd /usr/pkgsrc/uwm-pkgsrc-wip/$pkg
+    bmake install
+done
+for pkg in denyhosts; do
+    cd /usr/pkgsrc/wip/$pkg
+    bmake install
+done
 
 # Configure firewall
-iptables_config
+auto-enable-passwdqc
+cluster-iptables-config
 
 # After core_rpms.  Requires gcc.
 printf "Run harden script? y/[n] "
@@ -906,33 +864,12 @@ fi
 nfs_config
 ssh_config
 
-if [ $NODE_TYPE = head ]; then
-    ###################################################################
-    # Install user software independent of RPMS so that it will not be
-    # broken by yum updates.
-    
-    # Pkgsrc base
-    pkgsrc_prefix='/usr'
-    cat << EOM
+# Common packages
+for pkg in iperf; do
+    pkgin install -y $pkg
+done
+ganglia_install
 
-You may add a suffix on your local pkgsrc installation, such as -2016Q1.
-You *MUST* choose the same suffix when doing the pkgsrc installation.
-
-EOM
-    printf "Suffix on $pkgsrc_prefix/pkg[src]: [none] "
-    read pkgsrc_suffix
-    
-    pkgsrc_setup $pkgsrc_prefix "$pkgsrc_suffix"
-    pkgsrc_append_default_path $pkgsrc_prefix "$pkgsrc_suffix"
-
-    # Common packages
-    for pkg in wip/auto-admin net/iperf; do
-	pkgsrc_install_packages $pkgsrc_prefix "$pkgsrc_suffix" $pkg
-    done
-    ganglia_install $pkgsrc_prefix "$pkgsrc_suffix"
-fi
-
-# Requires auto-admin: Do after pkgsrc_setup
 disable_overcommit
 
 cluster_startup_scripts
@@ -944,9 +881,6 @@ case $NODE_TYPE in
     
     # Set up cluster-run env to allow running a command on all nodes
     # ( Initially for updating /etc/hosts )
-
-    # Enable authentication via outside LDAP server
-    # ldap_config
 
     # Set per-process memory limits to a fraction of RAM
     auto-set-memory-limits 16777216
@@ -975,7 +909,7 @@ esac
 # Do this LAST to ensure node is fully operational before going live
 case $NODE_TYPE in
 'head'|'compute')
-    slurm_install $pkgsrc_prefix "$pkgsrc_suffix"
+    slurm_install
     ;;
 *)
     ;;
@@ -986,7 +920,8 @@ mkdir -p /root/Save
 backup_file ~/anaconda-ks.cfg /root/Save
 
 if ! fgrep -q clusteradmin /etc/passwd; then
-    cluster-adduser cluster-admin
+    printf "Adding cluster-admin user...\n"
+    cluster-adduser clusteradmin
 fi
 
 printf "Checking/setting UID limits...\n"
@@ -999,3 +934,4 @@ if [ 0$reboot != 0n ]; then
     shutdown -r now
 fi
 
+touch /root/Save/node-configured
diff --git a/CentOS/Sys-scripts/ganglia-web-setup b/CentOS/Sys-scripts/ganglia-web-setup
--- a/CentOS/Sys-scripts/ganglia-web-setup
+++ b/CentOS/Sys-scripts/ganglia-web-setup
@@ -1,6 +1,5 @@
 #!/bin/sh -e
 
-
 ##########################################################################
 #   Function description:
 #       Pause until user presses return
@@ -15,10 +14,18 @@ pause()
 }
 
 # Caution: 
-# The line below is modified by install.sh. Be careful not to replace
-# %%PREFIX%% with a hard-coded prefix from an installed script.
-prefix=%%PREFIX%%
-yum install httpd php
+if which pkg_add > /dev/null 2>&1; then
+    pkg_add=`which pkg_add`
+    prefix=`echo ${pkg_add%/sbin/pkg_add}`
+else
+    printf "Cannot determine pkgsrc prefix.\n"
+    exit 1
+fi
+
+# yum install httpd php
+printf "Ganglia setup is currently disabled.\n"
+printf "Replace yum httpd with pkgsrc apache in $0.\n"
+exit
 
 ganglia=/var/lib/ganglia
 mkdir -p $ganglia/rrds
@@ -36,7 +43,7 @@ chmod -R u+rwX,g-w $ganglia_web
 #restorecon -R -v $ganglia_web
 #setsebool -P allow_httpd_anon_write=1
 # FIXME: Temporary hack
-echo 0 > /selinux/enforce
+setenforce Permissive
 
 DATADIR=$prefix/share/cluster-admin
 cp $DATADIR/WWW/global_styles.css $DATADIR/WWW/centos-power.jpg /var/www/html
diff --git a/Common/Sys-scripts/cluster-init-node b/Common/Sys-scripts/cluster-init-node
--- a/Common/Sys-scripts/cluster-init-node
+++ b/Common/Sys-scripts/cluster-init-node
@@ -14,7 +14,7 @@
 
 usage()
 {
-    printf "Usage: $0 hostname backup|compute|io\n"
+    printf "Usage: $0 host.domain backup|compute|io\n"
     exit 1
 }
 
@@ -35,6 +35,12 @@ if ! echo $node | fgrep -q '.'; then
 	exit 1
     fi
 fi
+
+if ! awk '{ print $2 }' /etc/hosts | fgrep -q $node; then
+    printf "Error: $node not found in /etc/hosts.\n"
+    exit 1
+fi
+
 node_type=$2
 
 case $node_type in
@@ -49,9 +55,23 @@ esac
 # login.mortimer
 # gateway=$2
 
+printf "Remove $node from all known_hosts files? [y]/n "
+read remove
+if [ 0$remove != 0n ]; then
+    cluster-remove-from-known-hosts $node
+fi
+
 case `auto-ostype` in
 RHEL)
     scp /etc/hosts ${node}:/etc
+
+    # FIXME: Use interface
+    if [ -e /etc/sysconfig/iptables ]; then
+	scp /etc/sysconfig/iptables ${node}:/etc/sysconfig
+    else
+	printf "No iptables to transfer.\n"
+    fi
+    
     
     # FIXME: Should this be handled by DHCP?
     ssh $node hostname $node
@@ -61,27 +81,42 @@ RHEL)
     # ssh $node 'if ! fgrep GATEWAY /etc/sysconfig/network; then echo "GATEWAY='$gateway'" >> /etc/sysconfig/network; fi; service network restart'
     
     printf "Installing basic tools...\n"
-    ssh $node yum install -y subversion rsync
+    ssh $node yum install -y subversion rsync gcc gcc-c++ gcc-gfortran
     
-    printf "Syncing pkgsrc...\n"
-    cluster-sync-pkgsrc $node_type $node
+    cat << EOM
+
+If all of your nodes run the same OS, you can use rsync to distribute 
+/usr/pkg* from the head node.  If they run different systems, /usr/pkg*
+should be maintained separatedly.
+
+EOM
+    printf "rsync pkgsrc? y/[n] "
+    read rsync_pkgsrc
+    if [ 0$rsync_pkgsrc = 0y ]; then
+	cluster-sync-pkgsrc $node_type $node
+    else
+	# Independent /usr/pkg
+	scp /usr/pkg/sbin/auto-binary-pkgsrc-setup \
+	    /usr/pkg/sbin/auto-os-release ${node}:
+	ssh $node 'env PATH=${PATH}:. auto-binary-pkgsrc-setup /usr/pkg auto'
+	ssh $node 'ln -sf /usr/pkg/etc/pkgsrc-non-exclusive.* /etc/profile.d'
+	ssh $node 'pkgin install -y nbpatch python27'
+	ssh $node 'cd /usr/pkgsrc && svn co https://outpaddling@github.com/outpaddling/uwm-pkgsrc-wip/trunk uwm-pkgsrc-wip'
+	ssh $node 'cd /usr/pkgsrc/uwm-pkgsrc-wip/auto-admin && bmake install'
+	ssh $node 'cd /usr/pkgsrc/uwm-pkgsrc-wip/cluster-admin && bmake install'
+    fi
     
-    # Pull ssh keys from node
-    # FIXME: Should not be needed and security risk if compute nodes
-    # behind on updates can access login node
-    # auto-ssh-reverse-authorize $node
+    # ssh $node hostname $node
+    # ssh $node \
+    #    "sed -i -e 's|HOSTNAME=.*|HOSTNAME=$node|' /etc/sysconfig/network"
+    ssh $node auto-set-hostname $node
+    # ssh $node 'if ! fgrep GATEWAY /etc/sysconfig/network; then echo "GATEWAY='$gateway'" >> /etc/sysconfig/network; fi; service network restart'
     
     conf_dir='/usr/local/cluster'
     ssh $node "mkdir -p $conf_dir && touch $conf_dir/init-done"
 
     printf "Installing yum updates...\n"
     ssh $node yum update -y
-    
-    printf "Reboot? ([y]/n) "
-    read reboot
-    if [ 0$reboot != 0n ]; then
-	ssh $node shutdown -r now
-    fi
     ;;
 
 FreeBSD)
@@ -95,7 +130,18 @@ FreeBSD)
     # ssh $node 'if ! fgrep GATEWAY /etc/sysconfig/network; then echo "GATEWAY='$gateway'" >> /etc/sysconfig/network; fi; service network restart'
     
     printf "Installing basic tools...\n"
-    ssh $node pkg install -y subversion rsync auto-admin
+    repo_dir=/usr/local/etc/pkg/repos
+    pkg_conf=$repo_dir/FreeBSD.conf
+    if [ -e $pkg_conf ]; then
+	printf "Installing $pkg_conf...\n"
+	ssh $node mkdir -p $repo_dir
+	scp $pkg_conf ${node}:$repo_dir
+    fi
+    # FIXME: Add cluster-admin
+    ssh -t $node env ASSUME_ALWAYS_YES=yes \
+	pkg install -y subversion rsync auto-admin
+    
+    rsync -av --delete /usr/ports ${node}:/usr
     
     # Pull ssh keys from node
     # FIXME: Should not be needed and security risk if compute nodes
@@ -106,7 +152,7 @@ FreeBSD)
     ssh $node "mkdir -p $conf_dir && touch $conf_dir/init-done"
 
     printf "Installing updates...\n"
-    ssh $node auto-update-system
+    ssh $node auto-update-system --binary
     ;;
 
 *)
@@ -114,3 +160,8 @@ FreeBSD)
     ;;
 esac
 
+printf "Reboot? [y]/n "
+read reboot
+if [ 0$reboot != 0n ]; then
+    ssh $node shutdown -r now
+fi
diff --git a/FreeBSD/Sys-scripts/cluster-setup b/FreeBSD/Sys-scripts/cluster-setup
--- a/FreeBSD/Sys-scripts/cluster-setup
+++ b/FreeBSD/Sys-scripts/cluster-setup
@@ -46,29 +46,6 @@ pause()
 }
 
 
-# FIXME: Base this on stop_service
-stop_pbs()
-{
-    printf "Stopping PBS daemons...\n"
-    if fgrep -q pbs_sched_enable $RC_CONF; then
-	service pbs_sched stop > /dev/null 2>&1 || true
-	sleep 2
-    fi
-    if fgrep -q pbs_server_enable $RC_CONF; then
-	service pbs_server stop > /dev/null 2>&1 || true
-	sleep 2
-    fi
-    if killall pbs_sched > /dev/null 2>&1; then
-	printf "Rogue pbs_sched terminated.\n"
-	sleep 2
-    fi
-    if killall pbs_server > /dev/null 2>&1; then
-	printf "Rogue pbs_server terminated.\n"
-	sleep 2
-    fi
-}
-
-
 ##########################################################################
 #   Function description:
 #       
@@ -87,7 +64,10 @@ stop_service()
 	printf "Usage: stop_service service\n"
     fi
     service $1 stop > /dev/null 2>&1 || true
+    sleep 2
     killall $1 > /dev/null 2>&1 || true
+    sleep 1
+    killall -9 $1 > /dev/null 2>&1 || true
 }
 
 
@@ -167,82 +147,8 @@ add_node_name()
 install_scheduler()
 {
     line
-    # Patch bug in openmpi run_depends
-    sed -i '.bak' 's|${SGE_ROOT}/fbsd-${ARCH}/qrsh|${SGE_ROOT}/bin/fbsd-${ARCH}/qrsh|g' \
-	/usr/ports/net/openmpi/Makefile
-    
-    cat << EOM
-Please choose a scheduler:
-
-1.. HTCondor
-2.. SGE (Requires X11)
-3.. SLURM
-4.. Torque PBS
-
-EOM
-
-    resp=' '
-    while [ 0$resp != 01 ] && [ 0$resp != 02 ] && [ 0$resp != 03 ] && [ 0$resp != 04 ]; do
-	resp=`auto-ask scheduler "Scheduler selection?" unknown`
-	case $resp in
-	1)
-	    install_packages sysutils/condor
-	    pause
-	    ;;
-	2)
-	    if ! auto-package-installed sysutils/sge62; then
-		install_packages sysutils/sge62
-	    
-		line
-		printf "You can ignore the post-install messages above.\n"
-		printf "The services will be configured automatically.\n"
-		pause
-		
-		# Source $LOCALBASE/sge/default/common/settings.csh
-		# All execution hosts must be administrative hosts during the installation.
-		# All hosts which you added to the list of administrative hosts during this
-		# installation procedure can now be installed.
-		line
-		printf "\nAll users should source $LOCALBASE/sge/<cell>/common/settings.[c]sh\n\n"
-		pause
-	    else
-		printf "SGE is already installed.\n"
-	    fi
-	    ;;
-	3)
-	    # Install dependencies
-	    install_packages sysutils/slurm-wlm
-	    
-	    # Reinstall with custom options
-	    reinstall=`auto-ask reinstall-slurm "Rebuild slurm with custom options?" n`
-	    if [ $reinstall = 'y' ]; then
-		install_port sysutils slurm-wlm
-	    fi
-	    ;;
-	4)
-	    if ! auto-package-installed sysutils/torque; then
-		line
-		install_packages sysutils/torque
-		# Package does not set permissions on spool directories
-		# Also, users are encouraged to update sysutils/torque
-		# to the latest version instead of using the package
-		#pkg_delete /var/db/pkg/torque*
-		#install_packages lang/perl devel/libtool
-		#printf "Reinstalling torque from port to ...\n"
-		#install_port sysutils torque
-	    
-		line
-		printf "You can ignore the post-install messages above.\n"
-		printf "The services will be configured automatically.\n"
-		pause
-	    fi
-	    ;;
-	*)
-	    printf "\nInvalid selection.\n\n"
-	    pause
-	    ;;
-	esac
-    done
+    install_packages sysutils/slurm-wlm
+    pw usermod slurm -d /home/slurm -m
 }
 
 
@@ -251,18 +157,8 @@ install_mpi()
     line
     # Install OpenMPI from source so we can choose build options
     if ! auto-package-installed net/openmpi; then
-	#if [ $AUTO_BUILD_FROM_SOURCE = 0 ]; then
-	    printf "\nInstalling openmpi dependencies from packages...\n"
-	    install_packages net/openmpi
-	    # FIXME: use auto-delete-packages
-	    # pkg_delete /var/db/pkg/openmpi*
-	#fi
-	
-	reinstall_mpi=`auto-ask rebuild-mpi "Reinstall openmpi from port to customize build?" y`
-	if [ $reinstall_mpi = 'y' ]; then
-	    pkg delete openmpi
-	    install_port net openmpi
-	fi
+	printf "\nInstalling openmpi...\n"
+	install_packages net/openmpi
     fi
 }
 
@@ -285,13 +181,6 @@ slurm_config()
 	    chmod 400 $munge_dir/munge.key
 	    printf "Generating munge key...\n"
 	    dd if=/dev/random bs=1 count=1024 > $munge_dir/munge.key
-	fi
-    else
-	# Could use munge_flags="--key-file $HEAD_USR/local/etc/munge/munge.key"
-	if [ ! -e $munge_dir/munge.key ]; then
-	    mkdir -p -m 0700 $munge_dir
-	    scp -p ${head_host}:$munge_dir/munge.key $munge_dir
-	    pause
 	fi
     fi
     
@@ -325,12 +214,10 @@ EOM
 	auto-enable-service slurmctld $0 > $LOG_DIR/slurmctld_enable 2>&1
 	service slurmctld restart
     else
-	scp ${head_host}:$slurm_conf $slurm_conf
-	service slurmd stop > /dev/null 2>&1 || true
+	stop_service slurmd
 	auto-enable-service slurmd $0 > $LOG_DIR/slurmd_enable 2>&1
 	service slurmd restart
     fi
-    pause
 }
 
 
@@ -340,6 +227,7 @@ scheduler_config()
     if auto-package-installed sysutils/slurm-wlm; then
 	slurm_config
     fi
+    printf "Done with slurm_config.\n"
     
     if auto-package-installed sysutils/condor; then
 	if [ ! -e $LOCALBASE/etc/condor_config ]; then
@@ -357,147 +245,11 @@ EOM
 	pause
 	$EDITOR $LOCALBASE/etc/condor_config*
     fi
-    
-    # SGE is reinstalled as a dependency of openmpi
-    if auto-package-installed sysutils/sge62; then
-	sge_config      # Run SGE setup tools
-	
-	printf "\nUpdating /etc/services for SGE...\n"
-	# Check /etc/services
-	if ! fgrep -q sge_qmaster /etc/services; then
-	    printf "sge_qmaster     6444/tcp   #Grid Engine Qmaster Service\n" >> /etc/services
-	    printf "sge_qmaster     6444/udp   #Grid Engine Qmaster Service\n" >> /etc/services
-	fi
-	if ! fgrep -q sge_qmaster /etc/services; then
-	    printf "sge_execd       6445/tcp   #Grid Engine Execution Service\n" >> /etc/services
-	    printf "sge_execd       6445/udp   #Grid Engine Execution Service\n" >> /etc/services
-	fi
-    fi
-    
-    if auto-package-installed sysutils/torque; then
-	if [ ! -e $TSPOOL ]; then
-	    cp -Rp $LOCALBASE/share/examples/torque$TSPOOL $TSPOOL
-	    chmod 1777 $TSPOOL/checkpoint $TSPOOL/spool $TSPOOL/undelivered
-	fi
-	
-	# Package missing arrays dir
-	mkdir -p $TSPOOL/server_priv/arrays
-	
-	# On compute nodes, put '$pbsserver ip.address.of.server' into
-	# $TSPOOL/mom_priv/config
-	
-	##################################################################
-	# Head node (torque server) only
-	#
-	
-	if [ $NODE_TYPE = "head" ]; then
-	    # Use main interface address on server if there are multiple
-	    # interfaces, not the local interface!  Torque will get
-	    # confused otherwise.
-	    # Also use short hostname, which must be in /etc/hosts.
-	    # If someone messes up /etc/hosts, we prefer a clear lookup
-	    # failure over getting the wrong address from DNS.
-	    hostname -s > $TSPOOL/server_name
-    
-	    # Cited as useful for dual nic servers, but not needed
-	    #printf "SERVERHOST\t$head_host\n" > $TSPOOL/torque.cfg
-	    #$EDITOR $TSPOOL/torque.cfg
-    
-	    # To configure queues on server, execute
-	    # $LOCALBASE/share/examples/torque/torque.setup <admin>
-	    stop_pbs
-
-	    # Annihilates server_priv/nodes.  Edit nodes AFTER this!
-	    #if [ ! -e $TSPOOL ]; then
-		printf "Running torque.setup...\n"
-		printf "y\n" | $LOCALBASE/share/examples/torque/torque.setup root \
-		    > $LOG_DIR/torque.setup
-		sleep 5
-		stop_pbs
-	    #fi
-    
-	    line
-	    nodes_file=$TSPOOL/server_priv/nodes
-	    nodes_backup=$LOCALBASE/cluster/server_priv-nodes
-	    if [ -e $nodes_backup ]; then
-		cp $nodes_backup $nodes_file
-	    fi
-	    cat << EOM
-
-Editing $nodes_file...
-
-Add names of existing compute nodes and options.  Compute nodes that are
-not yet operational should not be added at this time.
-
-EOM
-	    printf "Press enter when ready to enter the editor..."
-	    read junk
-	    $EDITOR $nodes_file
-	    cp $nodes_file $nodes_backup
-
-	    # auto-enable-service doesn't start services that are already
-	    # configured in rc.conf
-	    auto-enable-service pbs_server cluster-setup \
-		> $LOG_DIR/pbs_server_enable 2>&1
-	    sleep 2
-	    service pbs_server restart 2> $LOG_DIR/pbs_server_start
-	    sleep 2
-
-	    auto-enable-service pbs_sched cluster-setup 
-		> $LOG_DIR/pbs_sched_enable 2>&1
-	    sleep 2
-	    service pbs_sched restart 2> $LOG_DIR/pbs_sched_start
-	    sleep 2
-	else
-	    # Use local address of head node on compute nodes.  If
-	    # head node has multiple interfaces, the DNS entry will
-	    # provide the public interface IP rather than the private
-	    # cluster IP.
-	    # Also use short hostname, which must be in /etc/hosts.
-	    # If someone messes up /etc/hosts, we prefer a clear lookup
-	    # failure over getting the wrong address from DNS.
-	    printf "$head_host\n" > $TSPOOL/server_name
-    
-	    line
-	    #printf "\nAdd `hostname -s` to server_priv/nodes on the server\n"
-	    #printf "and restart pbs_server.\n\n"
-	    #pause
-	    
-	    printf "Adding $(hostname -s) to server_priv/nodes on $head_host\n"
-	    ssh $head_host auto-append-line "$(hostname -s)" \
-		"$(hostname -s)" $TSPOOL/server_priv/nodes \
-		cluster-setup
-	    ssh $head_host service pbs_server restart
-	    
-	    if fgrep -q pbs_mom $RC_CONF; then
-		if ! service pbs_mom stop > /dev/null 2>&1; then
-		    if killall pbs_mom > /dev/null 2>&1; then
-			printf "Old pbs_mom terminated.\n"
-		    fi
-		fi
-	    fi
-
-	    # On compute nodes, add the following line to $RC_CONF:
-	    # pbs_mom_enable="YES"
-	    auto-enable-service pbs_mom cluster-setup \
-		> $LOG_DIR/pbs_mom_enable 2>&1
-	    sleep 5
-	    service pbs_mom restart
-	    ssh $head_host pbsnodes
-	    # printf "\nTest this node by running 'pbsnodes' on head node.\n\n"
-	    pause
-	fi
-	
-	# Change torque/spool and torque/undelivered to 777?
-	# Does not appear necessary anymore.
-    fi
 }
 
 
-# Currently must come after Torque setup.  Reorg to consolidate scheduler conf
 nfs_config()
 {
-    df
     cat << EOM
 
 Some schedulers require a shared spool or config directory.  Check the
@@ -517,6 +269,10 @@ EOM
 	return
     fi
 
+    # FIXME: Submit PR
+    # NFS may fail to start without this, even if using ZFS
+    touch /etc/exports
+    
     auto-enable-service -s statd rpc_statd $0
     auto-enable-service -s lockd rpc_lockd $0
     
@@ -526,13 +282,17 @@ EOM
 	# Export /usr (which should include /usr/home)
 	# FIXME: Make sure NFS server is enabled in rc.conf first
 	# Does not work for multi-homed host
-	# ip=`fgrep $head_host /etc/hosts | awk ' { print $1 }' | uniq`
-	subnet=`auto-ask subnet "Subnet for NFS?" 192.168.0.0`
+	# ip=`fgrep $head_host $HOSTS | awk ' { print $1 }' | uniq`
+	subnet=`auto-ask subnet "\nSubnet for NFS?" 192.168.0.0`
 	
 	share='x'
 	while [ 0$share != 0 ]; do
+	    line
+	    printf "\nMounted filesystems:\n\n"
 	    df
-	    printf "Directory to export? [Press enter to quit] "
+	    printf "\nCurrent mounts:\n\n"
+	    showmount -e
+	    printf "\nDirectory to export? [Press enter to quit] "
 	    read share
 	    
 	    if [ 0$share != 0 ]; then
@@ -563,6 +323,7 @@ EOM
 
 	host='x'
 	while [ 0$host != 0 ]; do
+	    df
 	    printf "\nHost name of NFS server? [Press enter to quit] "
 	    read host
 	    
@@ -601,96 +362,9 @@ EOM
 		mount $share
 	    fi
 	done
-    
-	# FIXME: Find a way to list torque nodes that doesn't depend on
-	# a specific NFS mount.
-	# Add name of node to master list
-	#if auto-package-installed sysutils/torque; then
-	#    add_node_name `hostname -s` $HEAD_USR/local/cluster/torque_nodes
-	#fi
 	;;
 	
     *)
-	;;
-    esac
-}
-
-
-# Must come after NFS setup
-sge_config()
-{
-    case $NODE_TYPE in
-    "head")
-	# Configure SGE master
-	if auto-package-installed sysutils/sge62; then
-	    #cd $LOCALBASE/sge
-	    # -csp is for added security
-	    #./install_qmaster -csp
-	    #cd $start_dir
-	    cell=`auto-ask sge-cell "SGE cell name [default='default']?" default`
-	    if [ 0$cell = 0 ]; then
-		cell='default'
-	    fi
-	    
-	    if ! fgrep -q "sge_cell" $RC_CONF; then
-		printf "sge_cell=\"$cell\"\n" >> $RC_CONF
-	    fi
-	    if ! fgrep -q "sge_qmaster" $RC_CONF; then
-		printf "sge_qmaster_enable=\"YES\"\n" >> $RC_CONF
-	    fi
-	    
-	    if [ ! -e $LOCALBASE/sge/$cell ]; then
-		printf "\nRunning $LOCALBASE/sge/install_qmaster...\n\n"
-		pause
-		save_cwd=`pwd`
-		cd $LOCALBASE/sge
-		./install_qmaster
-		cd $save_cwd
-	    fi
-	fi
-	;;
-    compute)
-	# Configure SGE node
-	if auto-package-installed sysutils/sge62; then
-	    #cd $LOCALBASE/sge
-	    #./install_execd
-	    #cd $start_dir
-	    
-	    cell=`auto-ask sge-cell "SGE cell name [default='default']?" default`
-	    if [ 0$cell = 0 ]; then
-		cell='default'
-	    fi
-	    if ! fgrep -q "sge_cell" $RC_CONF; then
-		printf "sge_cell=\"$cell\"\n" >> $RC_CONF
-	    fi
-	    if ! fgrep -q "sge_execd" $RC_CONF; then
-		printf "sge_execd_enable=\"YES\"\n" >> $RC_CONF
-	    fi
-	    
-	    # FIXME: Don't expect HEAD_USR - let user choose mounts
-	    # Link cell directory or whole SGE directory from head to
-	    # $LOCALBASE/sge
-	    #ln -sf $HEAD_USR/local/sge/$cell $LOCALBASE/sge
-	    
-	    # 
-	    cat << EOM
-	
-Ready to run SGE setup tool...
-Make sure $(hostname) is configured as an administrative host
-On head node: Run qconf -sh to check and qconf -ah to add.
-
-EOM
-	    pause
-    
-	    #if [ ! -e $LOCALBASE/sge/$cell ]; then
-		printf "\nRunning $LOCALBASE/sge/install_execd...\n\n"
-		pause
-		save_cwd=`pwd`
-		cd $LOCALBASE/sge
-		./install_execd
-		cd $save_cwd
-	    #fi
-	fi
 	;;
     esac
 }
@@ -915,9 +589,6 @@ EOM
     if [ $NODE_TYPE = 'head' ]; then
 	# Disable prompting for new hosts, etc.
 	cluster-update-ssh_config
-    else
-	# Add this host to authorized keys for root on head node(s)
-	auto-ssh-authorize $head_host
     fi
 }
 
@@ -994,16 +665,9 @@ update_system()
     line
     printf "Updating system clock...\n"
     stop_service ntpd
-    if killall -9 ntpd > /dev/null 2>&1; then
-	printf "Killed rogue ntp.\n"
-    fi
     ntpdate -u pool.ntp.org
     auto-enable-service ntpd cluster-setup > /dev/null 2>&1
     service ntpd restart
-    local update=`auto-ask update-system 'Update system?' y`
-    if [ $update = y ]; then
-	auto-update-system
-    fi
 }
 
 
@@ -1045,7 +709,8 @@ install_common_tools()
 get_port_install_method()
 {
     line
-    resp=`auto-ask use-source "Build ports from source?" n`
+    #resp=`auto-ask use-source "Build ports from source?" n`
+    resp=n
     if [ 0$resp = 0'y' ]; then
 	export AUTO_BUILD_FROM_SOURCE='yes'
     else
@@ -1150,16 +815,15 @@ EOM
 
 verify_network()
 {
-    cat << EOM
-
-Before proceeding:
-
-1)  Confirm that your IP and netmask are correct in /etc/rc.conf.
-
-2)  Confirm that /etc/hosts contains a correct entry for each interface.
-
-EOM
+    line
+    printf "\nConfirm that your IP and netmask are correct in $RC_CONF.\n\n"
     pause
+    $EDITOR $RC_CONF
+
+    line
+    printf "\nConfirm that $HOSTS contains a correct entry for each interface.\n\n"
+    pause
+    $EDITOR $HOSTS
 }
 
 
@@ -1177,15 +841,12 @@ EOM
 
 get_head_host()
 {
-    printf 'Make sure /etc/hosts is up-to-date.\n'
-    pause
-    
     if [ $NODE_TYPE = "compute" ]; then
 	# If cluster-setup was previously completed on this node,
 	# get head node from configuration, otherwise ask.
 	head_host=''
 	while [ 0$head_host = 0 ]; do
-	    head_host=`auto-ask head-hostname "Short hostname of head node?" login`
+	    head_host=`auto-ask head-hostname "\nShort hostname of head node?" login`
 	done
     else
 	head_host=`hostname -s`
@@ -1226,20 +887,15 @@ done
 #   Set common variables
 ##########################################################################
 
-EDITOR=`auto-ask editor 'What is your preferred editor?' $EDITOR`
-export EDITOR
-
-printf 'If you have an old /etc/hosts.allow to restore, do it now.\n'
-pause
-$EDITOR /etc/hosts.allow
-
 # Recommended layout for dedicated hardware:
 # Use netmask of 255.255.128.0.
 MAX_NODES=60000
 
 # Misc
-LOCALBASE="/usr/local"
-RC_CONF='/etc/rc.conf'
+LOCALBASE=/usr/local
+RC_CONF=/etc/rc.conf
+HOSTS=/etc/hosts
+HOSTS_ALLOW=/etc/hosts.allow
 START_DIR=`pwd`
 APACHE_PKG=apache24
 
@@ -1252,8 +908,6 @@ pause
 
 # Source for default files
 DATADIR=$LOCALBASE/share/cluster-admin
-
-TSPOOL="/var/spool/torque"
 
 # Needed by openjdk, bash, etc.
 auto-add-fdesc-mount
@@ -1271,15 +925,36 @@ esac
 if [ $NODE_TYPE = head ]; then
     CLUSTER_DATA="$LOCALBASE/cluster"
     mkdir -p $CLUSTER_DATA
+
+    if [ -z $EDITOR ]; then
+	EDITOR=vi
+	export EDITOR
+    fi
+    
+    printf "\nIf you have an old $HOSTS_ALLOW to restore, do it now.\n\n"
+    pause
+    $EDITOR $HOSTS_ALLOW
 fi
 
 verify_network
-HEAD_IP=`auto-ask head-ip 'IP address of head node LOCAL interface?' 192.168.0.2`
+HEAD_IP=`auto-ask head-ip '\nIP address of head node LOCAL interface?' 192.168.0.2`
 NETMASK=`auto-ask netmask 'Netmask for local network?' 255.255.128.0`
 
 ##########################################################################
 #   Begin setup
 ##########################################################################
+
+if [ $NODE_TYPE = head ]; then
+    latest=`auto-ask latest "Use latest packages instead of quarterly?" y`
+    if [ $latest = y ]; then
+	mkdir -p $LOCALBASE/etc/pkg/repos
+	cat << EOM > $LOCALBASE/etc/pkg/repos/FreeBSD.conf
+FreeBSD: {
+  url: "pkg+http://pkg.FreeBSD.org/\${ABI}/latest"
+}
+EOM
+    fi
+fi
 
 # The following configuration must be done on all nodes, although
 # different node types may be configured differently.
@@ -1306,8 +981,6 @@ case $NODE_TYPE in
     # Install after scheduler.  OpenMPI port has options for scheduler
     # integration.
     install_mpi
-    ssh $head_host cluster-update-ssh_config
-    cluster-update-ssh_config
     ;;
 *)
     ;;
@@ -1326,10 +999,9 @@ if ! fgrep -q clusteradmin /etc/passwd; then
 Adding clusteradmin user...
 
 EOM
-    cluster-groupadd clusteradmin -g 1000
-    cluster-useradd clusteradmin 1000 clusteradmin 'Cluster Administrator' /bin/tcsh
+    cluster-groupadd clusteradmin -g 1000 || true
+    cluster-useradd clusteradmin 1000 clusteradmin 'Cluster Administrator' /bin/tcsh || true
 fi
 
 # Reboot to test new config after initial setup
 reboot_maybe
-
