Add ssh check to cluster-down-nodes
git-svn-id: file:///home/bacon/SVN/spcm/cluster-admin-0.3@292 fc83dafb-f549-e211-8a70-0017315c2eee

diff --git a/Common/User-scripts/cluster-down-nodes b/Common/User-scripts/cluster-down-nodes
--- a/Common/User-scripts/cluster-down-nodes
+++ b/Common/User-scripts/cluster-down-nodes
@@ -3,8 +3,13 @@
 status=0
 for node in `cluster-compute-nodes`; do
     if ! ping -c 1 $node > /dev/null 2>&1; then
-	echo $node
+	printf "$node is not responding to ping.\n"
 	status=1
+    else
+	if ! ssh $node hostname > /dev/null 2>&1; then
+	    printf "Cannot ssh to $node.\n"
+	    status=1
+	fi
     fi
 done
 exit $status
