node-{top,iostat,netstat,ps}: Support non-indexed compute node names

diff --git a/Common/User-scripts/node-iostat b/Common/User-scripts/node-iostat
--- a/Common/User-scripts/node-iostat
+++ b/Common/User-scripts/node-iostat
@@ -15,8 +15,8 @@ usage()
 
 Usage: $0 complete-node-name|compute-node-index
 
-If the argument does not begin with compute-, raid-, vis-, or login-,
-then compute- is automatically prepended.
+If the compute-<argument> is a valid compute node host name, then compute-
+is automatically prepended.
 
 Example:
     node-iostat 002         # same as node-iostat compute-002
@@ -40,8 +40,14 @@ fi
 
 node=$1
 shift
-if ! echo $node | egrep -q '^compute-|^raid-|^vis-|^login-'; then
+if [ 0$(node-type compute-$node) = 0compute ]; then
     node=compute-$node
+fi
+
+if ! (awk '{ print $2 }' /etc/hosts | fgrep -x $node || \
+    awk '{ print $3 }' /etc/hosts | fgrep -x $node); then
+    printf "$0: $node not found in /etc/hosts.\n"
+    exit 1
 fi
 
 case $(auto-ostype) in
