Fix user add for FreeBSD
git-svn-id: file:///home/bacon/SVN/spcm/cluster-admin-0.3@77 fc83dafb-f549-e211-8a70-0017315c2eee

diff --git a/FreeBSD/Scripts/cluster-sync-user b/FreeBSD/Scripts/cluster-sync-user
--- a/FreeBSD/Scripts/cluster-sync-user
+++ b/FreeBSD/Scripts/cluster-sync-user
@@ -30,7 +30,9 @@ fi
 user_name=$1
 
 for node in `cluster-compute-nodes`; do
-    echo $node
-    node-sync-user $node $user_name
+    echo $node $user_name
+    if ! node-sync-user $node $user_name; then
+	printf "Error syncing to $node.\n"
+    fi
 done
 
