cluster-software-manager: Redesign for portability, add pkgsrc support

diff --git a/Common/Sys-scripts/cluster-software-manager b/Common/Sys-scripts/cluster-software-manager
--- a/Common/Sys-scripts/cluster-software-manager
+++ b/Common/Sys-scripts/cluster-software-manager
@@ -84,11 +84,44 @@ fi
 
 case $(auto-ostype) in
 FreeBSD)
-    while true
-    do
-	clear
-	spcm-banner
+    installed_cmd='pkg info'
+    available_cmd='pkg search ".*"'
+    search_cmd='pkg search'
+    install_cmd='pkg install -y'
+    remove_cmd='pkg remove -y'
+    autoremove_cmd='pkg autoremove -y'
+    ;;
+
+Darwin|NetBSD|RHEL)
+    if ! which pkgin; then
 	cat << EOM
+
+$0 currently depends on pkgsrc binary packages and pkgin
+command has been found.
+
+EOM
+	exit 1
+    fi
+    installed_cmd='pkgin list'
+    available_cmd='pkgin avail'
+    search_cmd='pkgin search'
+    install_cmd='pkgin -y install'
+    remove_cmd='pkgin -y remove'
+    autoremove_cmd='pkgin -y autoremove'
+    ;;
+
+*)
+    printf "$0: Not supported on $(auto-ostype).\n"
+    exit 1
+    ;;
+
+esac
+
+while true
+do
+    clear
+    spcm-banner
+    cat << EOM
 
 To see ports by category, run "ls /usr/ports" and e.g. "ls /usr/ports/audio"
 or browse the collection at https://www.freebsd.org/ports/index.html.
@@ -105,78 +138,70 @@ but there could be issues installing new packages alongside much older ones.
 Q.. Quit
 
 EOM
+
+    read -p 'Selection? ' resp
+    case 0$resp in
+    01)
+	select_node_type
+	if [ 0$NODE_TYPE != 0 ]; then
+	    $SSH_NODE $installed_cmd | more
+	    printf "$($SSH_NODE pkg info | wc -l) packages installed.\n"
+	    pause
+	fi
+	;;
+
+    02)
+	tmpfile=.auto-software-manager-packages.txt
+	$search_cmd '.*' > $tmpfile
+	more $tmpfile
+	printf "$(cat $tmpfile | wc -l) packages available.\n"
+	rm -f $tmpfile
+	pause
+	;;
+
+    03)
+	read -p 'Enter any part of the package name: ' pattern
+	$search_cmd "$pattern" | more
+	pause
+	;;
     
-	read -p 'Selection? ' resp
-	case 0$resp in
-	01)
-	    select_node_type
-	    if [ 0$NODE_TYPE != 0 ]; then
-		$SSH_NODE pkg info | more
-		printf "$($SSH_NODE pkg info | wc -l) packages installed.\n"
+    04)
+	select_node_type
+	if [ 0$NODE_TYPE != 0 ]; then
+	    read -p 'Enter the package name(s): ' names
+	    if [ 0"$names" != 0 ]; then
+		if [ $NODE_TYPE = head ]; then
+		    $install_cmd $names
+		else
+		    cluster-run "$install_cmd $names" $NODE_TYPE
+		fi
 		pause
 	    fi
-	    ;;
+	fi
+	;;
     
-	02)
-	    tmpfile=.auto-software-manager-packages.txt
-	    pkg search '.*' > $tmpfile
-	    more $tmpfile
-	    printf "$(cat $tmpfile | wc -l) packages available.\n"
-	    rm -f $tmpfile
-	    pause
-	    ;;
-    
-	03)
-	    read -p 'Enter any part of the package name: ' pattern
-	    pkg search "$pattern" | more
-	    pause
-	    ;;
-	
-	04)
-	    select_node_type
-	    if [ 0$NODE_TYPE != 0 ]; then
-		read -p 'Enter the package name(s): ' names
-		if [ 0"$names" != 0 ]; then
-		    if [ $NODE_TYPE = head ]; then
-			pkg install -y $names
-		    else
-			cluster-run "pkg install -y $names" $NODE_TYPE
-		    fi
-		    pause
+    05)
+	select_node_type
+	if [ 0$NODE_TYPE != 0 ]; then
+	    read -p 'Enter the package name(s): ' names
+	    if [ 0"$names" != 0 ]; then
+		if [ $NODE_TYPE = head ]; then
+		    ($remove_cmd $names; $autoremove_cmd) || true
+		else
+		    cluster-run \
+			"($remove_cmd $names; $autoremove_cmd) || true" \
+			$NODE_TYPE
 		fi
+		pause
 	    fi
-	    ;;
-	
-	05)
-	    select_node_type
-	    if [ 0$NODE_TYPE != 0 ]; then
-		read -p 'Enter the package name(s): ' names
-		if [ 0"$names" != 0 ]; then
-		    if [ $NODE_TYPE = head ]; then
-			(pkg remove $names; pkg autoremove -y) || true
-		    else
-			cluster-run \
-			    "(pkg remove -y $names; pkg autoremove -y) || true" \
-			    $NODE_TYPE
-		    fi
-		    pause
-		fi
-	    fi
-	    ;;
-	
-	0Q|0q)
-	    exit 0
-	    ;;
+	fi
+	;;
     
-	*)
-	    printf "Invalid option: $resp\n"
-	esac
-    done
-    ;;
+    0Q|0q)
+	exit 0
+	;;
 
-*)
-    printf "$0: Not supported on $(auto-ostype).\n"
-    pause
-    ;;
-
-esac
+    *)
+	printf "Invalid option: $resp\n"
+    esac
+done
