Continue after certain non-zero ssh commands
git-svn-id: file:///home/bacon/SVN/spcm/cluster-admin-0.4@548 fc83dafb-f549-e211-8a70-0017315c2eee

diff --git a/Common/Sys-scripts/cluster-update-io-nodes b/Common/Sys-scripts/cluster-update-io-nodes
--- a/Common/Sys-scripts/cluster-update-io-nodes
+++ b/Common/Sys-scripts/cluster-update-io-nodes
@@ -1,6 +1,5 @@
 #!/bin/sh -e
 
-
 ##########################################################################
 #   Function description:
 #       Pause until user presses return
@@ -22,10 +21,11 @@ for node in `cluster-io-nodes` `cluster-zfs-nodes`; do
     ssh $node w
     pause
     ssh -t $node iftop
-    ssh -t $node iftop -i ib0 || true
+    ssh -t $node iftop -i ib0 || true   # May not be an IB interface
     printf "Update? y/[n] "
     read update
     if [ 0$update = 0y ]; then
-	ssh -t $node auto-update-system --binary
+	# CentOS 7 ssh always returns non-zero when rebooting
+	ssh -t $node auto-update-system --binary+reboot || true
     fi
 done
diff --git a/Common/Sys-scripts/cluster-update-vis-nodes b/Common/Sys-scripts/cluster-update-vis-nodes
--- a/Common/Sys-scripts/cluster-update-vis-nodes
+++ b/Common/Sys-scripts/cluster-update-vis-nodes
@@ -1,6 +1,5 @@
 #!/bin/sh -e
 
-
 ##########################################################################
 #   Function description:
 #       Pause until user presses return
@@ -19,12 +18,12 @@ for node in `cluster-vis-nodes`; do
     ssh $node w
     pause
     ssh -t $node iftop
-    ssh -t $node iftop -i ib0 || true
+    ssh -t $node iftop -i ib0 || true   # May not be an IB interface
     printf "Update? y/[n] "
     read update
     if [ 0$update = 0y ]; then
-	ssh $node "wall 'The visualization node will be rebooted shortly in order to complete installation of important security updates.  It should be available again within a few minutes.'"
-	ssh -t $node auto-update-system
+	ssh $node "wall 'The visualization node will be rebooted shortly in order to complete installation of important security updates.  It should be available again within a few minutes.'" || true
+	# CentOS 7 ssh always returns non-zero when rebooting
+	ssh -t $node auto-update-system --binary+reboot || true
     fi
 done
-
