Replace SLURM with LPJS in all cluster update scripts

diff --git a/Common/Sys-scripts/lpjs-update-idle-nodes b/Common/Sys-scripts/lpjs-update-idle-nodes
--- a/Common/Sys-scripts/lpjs-update-idle-nodes
+++ b/Common/Sys-scripts/lpjs-update-idle-nodes
@@ -5,9 +5,6 @@
 #       Run system updates on idle nodes
 #       First drain all nodes and then update nodes in a drained state
 #
-#   Arguments:
-#       Log directory
-#       
 #   History:
 #   Date        Name        Modification
 #   2014-11-05  J Bacon     Begin
@@ -15,7 +12,7 @@
 
 usage()
 {
-    printf "Usage: $0 log-directory\n"
+    printf "Usage: $0\n"
     exit 1
 }
 
@@ -39,19 +36,19 @@ pause()
 ##########################################################################
 
 case $# in
-1)
+0)
     ;;
 *)
     usage
     ;;
 esac
 
-readonly log_dir="$1"
+readonly log_dir="/usr/local/var/log/lpjs"
 readonly lock_file="$log_dir/lockfile"
 if [ -e "$lock_file" ]; then
     printf "Another instance of $0 is currently running.\n"
     printf "Remove $lock_file to override.\n"
-    slurm-resume-updated-nodes "$log_dir" || true
+    lpjs-resume-updated-nodes || true
     exit
 fi
 touch "$lock_file"
@@ -69,8 +66,8 @@ chmod 750 `dirname "$updated_nodes_file"`
 if test -t 0; then
     cat << EOM
 
-All nodes will be set to a draining state and will not accept new jobs
-until they have been updated.
+All nodes will be paused and will not accept new jobs until they have
+been updated.
 
 If there are jobs currently running, this script will need to be run
 repeatedly until all current jobs are finished in order to update all nodes.
@@ -87,37 +84,34 @@ EOM
 fi
 
 cd "$log_dir"
-sinfo -o '%n %T %E' -h | sort | uniq
+lpjs nodes
 wc -l "$updated_nodes_file"
 updated=0
 
 # Why is this here?
 # rm -f "$lock_file"
 
-if [ `squeue | awk '$5 == "S"' | wc -l` != 0 ]; then
-    printf "There are suspended jobs.  It is not safe to run updates.\n"
-    exit 1
-fi
+# FIXME: Check for suspended jobs?
 
-nodes=`sinfo -o %n -h | sort | uniq`
+nodes=`lpjs nodes | awk 'NF == 8 && $1 != "Hostname" && $1 != "Total" { print $1 }'`
 
 # First pass simply drains as many nodes as possible, as quickly as possible,
 # to prevent jobs from allocating them before they're updated.
 for node in $nodes; do
     # Update node if it's not in the updated list
     if ! fgrep -q $node "$updated_nodes_file"; then
-	state=`sinfo -n $node -o %T -h`
+	state=`lpjs nodes | awk -v node=$node '$1 == node { print $2 }'`
 	case $state in
-	'drained'|'drained*')
+	'pause')
 	    ;;
 	
-	'down'|'down*')
+	'down')
 	    # Don't change state of down nodes!
 	    ;;
 	
 	*)
-	    scontrol update nodename=$node state=drain \
-		reason=slurm-update-idle-nodes
+	    # FIXME: Add "updating" state, same as pause
+	    lpjs nodes pause $node
 	    ;;
 	esac
     fi
@@ -127,49 +121,44 @@ done
 for node in $nodes; do
     # Update drained nodes not in the updated list
     if ! fgrep -q $node "$updated_nodes_file"; then
-	state=`sinfo -n $node -o %T -h`
+	state=`lpjs nodes | awk -v node=$node '$1 == node { print $2 }'`
 	case $state in
-	'drained'|'drained*')
-	    reason=`sinfo -o %E -h --nodes=$node`
-	    if [ $reason = slurm-update-idle-nodes ]; then
-		printf "Updating $node...\n"
-		# Why was this here?
-		#scontrol update nodename=$node state=down \
-		#    reason=slurm-update-idle-nodes
+	'pause')
+	    printf "Updating $node...\n"
+	    # Why was this here?
+	    #scontrol update nodename=$node state=down \
+	    #    reason=lpjs-update-idle-nodes
+	    
+	    # Install all available binary updates and reboot
+	    # Don't stall updates on a node that's swallowing ssh
+	    # connections due to thrashing, NFS hangups, etc.
+	    if ssh -t -o ConnectTimeout=10 $node auto-update-system --binary; then
 		
-		# Install all available binary updates and reboot
-		# Don't stall updates on a node that's swallowing ssh
-		# connections due to thrashing, NFS hangups, etc.
-		if ssh -t -o ConnectTimeout=10 $node auto-update-system --binary; then
-		    
-		    # --binary+reboot always returns non-zero
-		    # on RHEL 7, so reboot separately
-		    ssh $node shutdown -r now || true
-		    
-		    # shutdown may take some time to disable sshd
-		    # This will prevent slurm-resume-updated-nodes from
-		    # resuming the node before the reboot.
-		    while ping -c 1 -q $node > /dev/null 2>&1; do
-			printf "Waiting for shutdown of $node...\n"
-			sleep 5
-		    done
-		    
-		    # Checked by slurm-resume-updated-nodes.  Node should
-		    # be unresponsive to ssh before adding to
-		    # updated_nodes_file as slurm-resume-updated-nodes will
-		    # resume it if it responds to ssh and is listed here.
-		    printf "$node `date`\n" >> "$updated_nodes_file"
-		    
-		    # This should cause the node to get set to down state
-		    # without changing "reason", assuming the node is unreachable
-		    # when this is run.
-		    # Not functioning as expected on Mortimer
-		    # scontrol update nodename=$node state=resume
-		else
-		    printf "Update failed.\n"
-		fi
+		# --binary+reboot always returns non-zero
+		# on RHEL 7, so reboot separately
+		ssh $node shutdown -r now || true
+		
+		# shutdown may take some time to disable sshd
+		# This will prevent lpjs-resume-updated-nodes from
+		# resuming the node before the reboot.
+		while ping -c 1 -q $node > /dev/null 2>&1; do
+		    printf "Waiting for shutdown of $node...\n"
+		    sleep 5
+		done
+		
+		# Checked by lpjs-resume-updated-nodes.  Node should
+		# be unresponsive to ssh before adding to
+		# updated_nodes_file as lpjs-resume-updated-nodes will
+		# resume it if it responds to ssh and is listed here.
+		printf "$node `date`\n" >> "$updated_nodes_file"
+		
+		# This should cause the node to get set to down state
+		# without changing "reason", assuming the node is unreachable
+		# when this is run.
+		# Not functioning as expected on Mortimer
+		# scontrol update nodename=$node state=resume
 	    else
-		printf "Skipping $node, down for $reason.\n"
+		printf "Update failed.\n"
 	    fi
 	    ;;
 
@@ -179,16 +168,15 @@ for node in $nodes; do
 	    
 	*)
 	    # If not updated and not drained, drain it now
-	    scontrol update nodename=$node state=drain \
-		reason=slurm-update-idle-nodes
+	    lpjs nodes pause $node
 	    ;;
 	esac
     fi
     
     # Resume all nodes that have been updated but are still marked down
     # or drained, but respond to ssh.
-    slurm-resume-updated-nodes "$log_dir" || true
+    lpjs-resume-updated-nodes || true
 done
-slurm-resume-all-updated-nodes "$log_dir"
+lpjs-resume-all-updated-nodes
 wc -l $updated_nodes_file
 rm -f "$lock_file"
