Clean up
git-svn-id: file:///home/bacon/SVN/spcm/cluster-admin-0.3@215 fc83dafb-f549-e211-8a70-0017315c2eee

diff --git a/Common/Sys-scripts/node-sync-user b/Common/Sys-scripts/node-sync-user
--- a/Common/Sys-scripts/node-sync-user
+++ b/Common/Sys-scripts/node-sync-user
@@ -37,10 +37,12 @@ group_id=`awk -F : -v user_name=$user_name '$1 == user_name { print $4 }' /etc/p
 gecos=`awk -F : -v user_name=$user_name '$1 == user_name { print $5 }' /etc/passwd`
 home=`awk -F : -v user_name=$user_name '$1 == user_name { print $6 }' /etc/passwd`
 shell=`awk -F : -v user_name=$user_name '$1 == user_name { print $7 }' /etc/passwd`
+#printf "$user_id $group_id $gecos $home $shell\n"
 
 # Create group first if necessary
 group_name=`awk -F : -v group_id=$group_id '$3 == group_id { print $1 }' /etc/group`
-printf "$node ${user_name}:$group_name...\n"
+#printf "$group_name\n"
+#printf "$node ${user_name}:$group_name...\n"
 
 case `uname` in
 Linux)
@@ -52,14 +54,16 @@ Linux)
 	-s $shell -u $user_id $user_name
     ;;
 FreeBSD)
-    ssh $node pw groupadd $group_name -g $group_id
+    if ! ssh $node pw groupadd $group_name -g $group_id; then
+	printf 'Group add failed.\n'
+    fi
 
     # Create user
-    ssh $node pw useradd $user_name -c "\"$gecos\"" -d $home -g $group_id \
+    ssh $node pw useradd $user_name -c "\"$gecos\"" -d $home -m -g $group_id \
 	-s $shell -u $user_id
     ;;
 *)
-    printf "$0: Invalid OS: `uname`\n"
+    printf "$0: Invalid OS: `uname`"
     exit 1
 esac
 
