Numerous improvements for FreeBSD
git-svn-id: file:///home/bacon/SVN/spcm/cluster-admin-0.4@520 fc83dafb-f549-e211-8a70-0017315c2eee

diff --git a/FreeBSD/Sys-scripts/cluster-portsnap b/FreeBSD/Sys-scripts/cluster-portsnap
--- a/FreeBSD/Sys-scripts/cluster-portsnap
+++ b/FreeBSD/Sys-scripts/cluster-portsnap
@@ -2,6 +2,8 @@
 
 portsnap fetch && portsnap update
 for node in `cluster-compute-nodes`; do
-    rsync -av --delete /usr/ports ${node}:/usr
+    if ! rsync -av --delete /usr/ports ${node}:/usr; then
+	printf "$node\n" >> cluster-portsnap-failed-nodes
+    fi
 done
 
