Minor bug fixes
git-svn-id: file:///home/bacon/SVN/spcm/cluster-admin-0.3@188 fc83dafb-f549-e211-8a70-0017315c2eee

diff --git a/FreeBSD/Sys-scripts/node-sync-user b/FreeBSD/Sys-scripts/node-sync-user
--- a/FreeBSD/Sys-scripts/node-sync-user
+++ b/FreeBSD/Sys-scripts/node-sync-user
@@ -54,7 +54,9 @@ Linux)
 	-s $shell -u $user_id $user_name
     ;;
 FreeBSD)
-    ssh $node pw groupadd $group_name -g $group_id
+    if ! ssh $node pw groupadd $group_name -g $group_id; then
+	printf 'Group add failed.\n'
+    fi
 
     # Create user
     ssh $node pw useradd $user_name -c "\"$gecos\"" -d $home -m -g $group_id \
